accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail, name="detail"),
    ]

djangonautic/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from portfoilo import views as my_site

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('portfoilo.urls')),
    path('about/',include('portfoilo.urls')),
    path('contact/', include('portfoilo.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfoilo/urls.py
from django.urls import path
from portfoilo import views

app_name = 'portfoilo'

urlpatterns = [
    path('', views.home_page, name="home"),
    path('home/', views.home_page, name="home"),
    path('about/', views.about_me, name="about"),
    path('contact/', views.contact_me, name="contact"),
    path('messages/', views.view_messages, name="view-messages"),
    path('components/', views.components, name="view-components"),
    ]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = HTMLField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,default=None) 

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

portfoilo/models.py
from django.db import models

class Comment(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    class Meta:
        app_label = 'portfoilo'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb',]

portfoilo/forms.py
from django import forms
from .models import Comment



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['email', 'subject', 'message']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('articles:list')

articles/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date');
    return render(request, 'articles/my_articles.html', { 'articles': articles })

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', { 'article': article })

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'form': form })

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return HttpResponse('homepage')
    # return render(request, 'homepage.html')

def about(request):
    return HttpResponse('about')
    # return render(request, 'about.html')

portfoilo/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import CommentForm
from .models import Comment  # Import your Comment model
from django.contrib.auth.decorators import login_required


def home_page(request): 
    # return HttpResponse("home page")
    articles = "fuck python"
    return render(request, 'portfoilo/home.html')

def about_me(request):
    return render(request, 'portfoilo/about.html')

# def contact_me(request):
#     return render(request, 'contact.html')

def contact_me(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            print("valid form")
            # Optionally, you can redirect to a success page or do other actions.
            # return redirect('home')
            return redirect('portfoilo:home',)
        else:
             return HttpResponse("error happened in submission of form")
    else:
        form = CommentForm()
    return render(request, 'portfoilo/contact.html', {'form': form})


@login_required(login_url="/accounts/login/")
def view_messages(request):
    messages = Comment.objects.all()  # Retrieve all messages from the database
    return render(request, 'portfoilo/feedback.html', {'messages': messages})
    

def components(request):
    return render(request, 'portfoilo/components.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base.html' %}
{% block content %}
    <script src="/static/js/slugify.js"></script>
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="/static/js/text-editor.js"></script>

    <div class="row" >
        <div class="col-md-10 col-md-offset-1">
            <div class="create-article">
                <h2>Create an Awesome New Article</h2>
                <form action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data" class="reveal-content" style="padding: 40px;">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title">Title:</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="id_slug">Slug:</label>
                        {{ form.slug }}
                    </div>
                    <div class="form-group">
                        <label for="id_body">Body:</label>
                        {{ form.body }}
                    </div>
                    <div class="form-group">
                        <label for="id_thumb">Thumbnail:</label>
                        {{ form.thumb }}
                    </div>
                    <input type="submit" value="Create" class="btn btn-default btn-lg">
                </form>
            </div>
        </div>
        
</div>
    </div>               
{% endblock %}

articles/templates/articles/article_detail.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="{% static '/css/basic.css' %}">
        <link rel="stylesheet" href="{% static '/css/index.css' %}">
    </head>
<body>
    <div class="container-button">

        <a href="/articles/" class="button-back">
          <div class="button__line"></div>
          <div class="button__line"></div>
          <span class="button__text">Back Home</span>
          <div class="button__drow1"></div>
          <div class="button__drow2"></div>
        </a>
      
      </div>
    <article dir="rtl">
                <div class="article-header">
                    <img src="{{ article.thumb.url }}" />
                        <h2>{{ article.title }}</h2>                       
                </div>
                <div class="article-detail">
                    <div class="article">                                           
                            {% autoescape off %}
                            <p>{{ article.body }}</p>
                            {% endautoescape %}
                            <h3>كتبه العبد الفقير إلى الله {{ article.author.username }}</h3>
                            <p>{{ article.date }}</p>
                    </div>       
                </div>
        </article>
</body>
</html>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Articles List</h1>
    <div class="articles">
    {% for article in articles %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>{{ article.snippet }}</p>
            <p>{{ article.date }}</p>
            <p class="author">added by {{ article.author.username }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

articles/templates/articles/my_articles.html
{% extends 'base.html' %}
{% block content %}
<div class="section-container">
  <div class="container">
    <div class="row">
      
     

      <div class="col-md-12">
     
      <div id="myCarousel" class="carousel slide projects-carousel">
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="row">
                
                  {% for article in articles %}
                    <div class="col-sm-4">

                    

                      <a href="./work.html" title="" class="black-image-project-hover">
                        <img src="{{ article.thumb.url }}" alt="" class="img-responsive">
                      </a>
                      <div class="card-container card-container-lg">
                        <h4>{{article.date}}</h4>
                        <h3>{{article.title}}</h3>
                        <p>{{article.author.username}}</p>
                        <a href="{% url 'articles:detail' slug=article.slug %}" title="" class="btn btn-default">Discover</a>
                      </div>
                    </div>
                    {% endfor %}
                   

                </div>
                <!--/row-->
            </div>
            <!--/item-->
            <div class="item">
                <div class="row">
                <!--/row-->
            </div>
            <!--/item-->
        </div>
        <!--/carousel-inner--> 

     </div>



    <!--/myCarousel-->
    </div>



    </div>
  </div>
</div>

{% endblock %}

portfoilo/templates/portfoilo/about.html
{% extends 'base.html' %}
{% block content %}

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">01 : About me</h1>
          </div>
          
          <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <div class="row">
                <div class="col-xs-12 col-md-6">
                  <h3>Senior Security Consultant</h3>
                  <p>A results-oriented Security Specialist with experience in VAPT services and leadership roles. Led and
                    delivered cybersecurity assessments for about 50 clients in Qatar, Malaysia and Singapore. Expertise in
                    leading teams to improve performance, engagement, and forging partnerships with internal and external
                    partners. Specializes in helping companies and organizations secure their infrastructure by assessing the
                    security posture from a red team perspective. Extensive experience in Web Application security and latest
                    attacks against multiple frameworks such as Django, Angular, Laravel, ASP.NET MVC, etc.
                    </p>
                  <h3>Ut enim ad minim </h3>
                  <p>Duis aute irure dolor in reprehenderit in voluptate velit esse
                  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                  proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
                  <h3>Maecenas luctus at sem quis varius</h3>
                  <p>
                  Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus iaculis magna sagittis elit sagittis, at hendrerit lorem venenatis. Morbi accumsan iaculis blandit. Cras ultrices hendrerit nisl.</p>
                </div>
                <div class="col-xs-12 col-md-6">
                  <img src="/static/pictures/profil.jpg" class="img-responsive" alt="">
                </div>
              </div>
            </div>
          </div>
          
          
       </div>
      </div>
    </div>
  </div>
  {% endblock %}

portfoilo/templates/portfoilo/components.html
{% extends 'base.html' %}
{% block content %}

<div class="section-container">
  
<!-- Add your site or app content here -->
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6">

        <div class="template-example">
          <h2 class="template-title-example">Text</h2>
          <p>This is bold and this is semi bold and <b>this is extra bold</b>. This is italic and this is extra light and this is light
          and this is regular. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

          <blockquote>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          </blockquote>
          
          </p>
        </div>

        <div class="template-example">
          <h2 class="template-title-example">Headings</h2>
          
          <table class="table table-bordered">
            <tr><td><h1>H1: Heading 1</h1></td></tr>
            <tr><td><h2>H2: Heading 2</h2></td></tr>
            <tr><td><h3>H3: Heading 3</h3></td></tr>
            <tr><td><h4>H4: Heading 4</h4></td></tr>
          </table>
          
        </div>

        
        <div class="template-example">
          <h2 class="template-title-example">List</h2>
          <div class="row">
            <div class="col-md-6">
              <h3 class="template-title-example">Ordered</h3>
              <ul>
                <li>Consectetur adipiscing elit</li>
                <li>Integer molestie lorem at massa</li>
                <li>Facilisis in pretium nisl aliquet</li>
                <li>Nulla volutpat aliquam velit</li>
              </ul>
            </div>
            <div class="col-md-6">
              <h3 class="template-title-example">Number</h3>
              <ol>
                <li>Consectetur adipiscing elit</li>
                <li>Integer molestie lorem at massa</li>
                <li>Facilisis in pretium nisl aliquet</li>
                <li>Nulla volutpat aliquam velit</li>
              </ol>
            </div>
          </div>
        </div>
        
      </div>

      <div class="col-xs-12 col-md-6">
        <div class="template-example">
          <h2 class="template-title-example">Icons</h2>
          
          <div class="row">
            
            <div class="col-md-6">
               <h3 class="template-title-example">Basic Icons</h2>
                <ul class="list-icons">
                  <li>
                    <span class="fa-icon">
                      <i class="fa fa-facebook"></i>
                    </span>
                  </li>
                  <li>
                    <span class="fa-icon">
                      <i class="fa fa-twitter"></i>
                    </span>
                  </li>
                  <li>
                    <span class="fa-icon">
                      <i class="fa fa-linkedin"></i>
                    </span>
                  </li>
                  <li>
                    <span class="fa-icon">
                      <i class="fa fa-instagram"></i>
                    </span>
                  </li>
                </ul>
            </div>

          </div>


          


        </div>

        <div class="template-example">
          <h2 class="template-title-example">Buttons</h2>
          <div class="row">
            <div class="col-md-6">
              <h3 class="template-title-example">Primary</h2>
              <div class="row">
                  <div class="col-md-6">
                  <p><a href="" class="btn btn-primary btn-lg">Primary Large</a></p>
                  <p><a href="" class="btn btn-primary">Primary </a></p>
                  <p><a href="" class="btn btn-primary btn-sm">Primary Small</a></p>
                </div>
              </div>

              
            </div>

            <div class="col-md-6">
              <h3 class="template-title-example">Default</h2>
              <div class="row">
                  <div class="col-md-6">
                  <p><a href="" class="btn btn-default btn-lg">Default Large</a></p>
                  <p><a href="" class="btn btn-default">Default </a></p>
                  <p><a href="" class="btn btn-default btn-sm">Default Small</a></p>
                </div>
              </div>

            </div>
          </div>
        </div>
        
        <div class="template-example">
          <h2 class="template-title-example">Inputs</h2>

            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
            </div>

            <div class="form-group">
              <select class="form-control">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
              </select>
            </div>

            <div class="form-group">
              <label class="checkbox-inline">
                <input 
                type="checkbox" id="inlineCheckbox1" value="option1"> Email me a copy
              </label>
              <label class="checkbox-inline">
                <input type="checkbox" id="inlineCheckbox2" value="option2"> I am a human
              </label>
            </div>

            <div class="form-group">
              <textarea class="form-control" rows="3" placeholder="Enter your message"></textarea>
            </div>
            
            <div class="alert alert-success" role="alert">Your message was successfully sent</div>
            <div class="alert alert-danger" role="alert">Your message has not been sent, restart</div>
        </div>




      </div>
    </div>
  </div>
</div>

{% endblock %}

portfoilo/templates/portfoilo/contact.html
{% extends 'base.html' %}
{% block content %}

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">03 : Contact me</h1>
          </div>
          
          <div class="row">
            <div class="col-md-10 col-md-offset-1">
               <form action="{% url 'portfoilo:contact' %}" method="post" class="reveal-content">
                {% csrf_token %}
                  <div class="row">
                    <div class="col-md-7">
                      <div class="form-group">
                        <input type="email" class="form-control" id="email" placeholder="Email" name="email">
                      </div>
                      <div class="form-group">
                        <input type="text" class="form-control" id="subject" placeholder="Subject" name="subject">
                      </div>
                      <div class="form-group">
                        <textarea class="form-control" rows="5" placeholder="Enter your message" name="message"></textarea>
                      </div>
                      <button type="submit" class="btn btn-default btn-lg">Send</button>
                    </div>
                    <div class="col-md-5 address-container">
                      <ul class="list-unstyled">
                        <li>
                          <span class="fa-icon">
                            <i class="fa fa-phone" aria-hidden="true"></i>
                          </span>
                          + 33 9 07 45 12 65
                        </li>
                        <li>
                          <span class="fa-icon">
                            <i class="fa fa-at" aria-hidden="true"></i>
                          </span>
                          e-mail@mail.io
                        </li>
                        <li>
                          <span class="fa-icon">
                            <i class="fa fa fa-map-marker" aria-hidden="true"></i>
                          </span>
                          42 rue Moulbert 75016 Paris
                        </li>
                      </ul>
                      <h3>Follow me on social networks</h3>
                      <a href="http://www.facebook.com" title="" class="fa-icon">
                        <i class="fa fa-facebook"></i>
                      </a>
                      <a href="http://www.twitter.com" title="" class="fa-icon">
                        <i class="fa fa-twitter"></i>
                      </a>
                      <a href="http://www.linkedin.com" title="" class="fa-icon">
                        <i class="fa fa-linkedin"></i>
                      </a>

                    </div>
                  </div>
                </form>
            </div>

          </div>
         
       </div>
      </div>
    </div>
  </div>


  {% endblock %}

portfoilo/templates/portfoilo/feedback.html
{% extends 'base.html' %}
{% block content %}

<div class="section-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="section-container-spacer text-center">
            <h1 class="h2">Messages from People</h1>
          </div>
          
          <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <div class="row">
                <div class="col-xs-12 col-md-6">
                  <h3>Messages:</h3>
                  <p>
                  

                    <p>email  ||
                    subject||
                    message</p>
    {% for message in messages %}
                      <p>{{ message.email }} ||
                       {{message.subject}} ||
                       {{message.message}} </p>
          
                      {% comment %} email = models.EmailField()
                      subject = models.CharField(max_length=255)
                      message = models.TextField() {% endcomment %}
       
    {% endfor %}
    </div>

                    </p>
                  
                </div>
                <div class="col-xs-12 col-md-6">
                  <img src="./assets/images/profil.jpg" class="img-responsive" alt="">
                </div>
              </div>
            </div>
          </div>
          
          
       </div>
      </div>
    </div>
  </div>
  {% endblock %}

portfoilo/templates/portfoilo/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">
  
  <link rel="apple-touch-icon" sizes="180x180" href="/static/pictures/apple-icon-180x180.png">
  <link href="/static/favicon.ico" rel="icon">

  <title>Title page</title>  

<link href="{% static '/css/homepage.css' %}" rel="stylesheet"></head>

<body class="minimal">
<div id="site-border-left"></div>
<div id="site-border-right"></div>
<div id="site-border-top"></div>
<div id="site-border-bottom"></div>
<!-- Add your content of header -->
<header>
  <nav class="navbar  navbar-fixed-top navbar-inverse">
    <div class="container">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav ">
          <li><a href="." title="">01 : Home</a></li>
          <li><a href="/articles" title="">02 : Blog</a></li>
          <li><a href="/about" title="">03 : About me</a></li>
          <li><a href="/contact" title="">04 : Contact</a></li>
          {% if user.is_authenticated %}
          <li><a href="/messages" title="">05 : Users' Messages</a></li>
          {% endif %}
        </ul>


      </div> 
    </div>
  </nav>
</header>
<!-- Add your site or app content here -->
  <div class="hero-full-container background-image-container white-text-container" style="background-image: url('/static/pictures/space.jpg')">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="hero-full-wrapper">
            <div class="text-content">
              <h1>Hello,<br>
                <span id="typed-strings">
                  <span>I'm Abdulah AlSolaiman</span>
                  <span>Independent Cybersecurity Researcher</span>
                  <span>and more importantly, a human.</span>
                </span>
                <span id="typed"></span>
              </h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<script>
  document.addEventListener("DOMContentLoaded", function (event) {
     type();
     movingBackgroundImage();
  });
</script>


<script type="text/javascript" src="/static/js/homepage.js"></script></body>

</html>

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonauts</title>
        <link rel="stylesheet" href="{% static '/css/styles.css' %}">
    </head>
    
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'portfoilo:home' %}"><img src="{% static '/pictures/logo.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>